# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Connor Smith
tagline:          'a brainspace'
description:      'a brainspace'
url:              http://connorsmith.github.io
baseurl:          /
resume:           http://connorsmith.github.io/public/connor-resume_20210502.pdf

author:
  name:           'Connor Smith'
  url:

paginate:         5

# Custom vars
version:          0.0.2

github:
  repo:           https://github.com/connorsmith/connorsmith.github.io

linkedin:         https://www.linkedin.com/in/conthesmith
googleplus:       https://plus.google.com/+ConnorSmithConnor/posts
strava:           http://www.strava.com/athletes/4374239
goodreads:        https://www.goodreads.com/user/show/3353185-connor
